name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (force install)
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install -g @capacitor/cli

      - name: Build Web App
        run: npm run build

      - name: Copy Web Assets to Android
        run: npx cap sync android

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChemistryLab-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
